import type { Lender } from "./types";

/**
 * ── Source confidence ───────────────────────────────────────────────────
 * sourceConfidence: "verified"   → name, rates, terms and rating cross-
 *   checked directly against the provider's own Play Store listing and/or
 *   official site (the original 9-lender set).
 * sourceConfidence: "aggregated" → pulled from third-party loan-comparison
 *   directories, not independently confirmed against the provider. Names
 *   and general positioning are real; exact rates, amounts and approval
 *   times are indicative and should be spot-checked before you rely on
 *   them. Several of these sites reuse near-identical rate templates
 *   across lenders, so treat the specific numbers as a starting point,
 *   not a fact.
 *
 * applyUrl: real, confidently-known official domains where I have them.
 * Where I wasn't confident I had the *correct* current domain for a
 * smaller lender, applyUrl points to a Google search for the official
 * site instead of a guessed URL — sending someone to the wrong financial
 * site is worse than one extra click.
 *
 * iconUrl: only set where pulled directly from a provider's live Play
 * Store listing. Left unset elsewhere — the UI falls back to a plain
 * monogram tile, which is intentional rather than a bug.
 *
 * playRating / playReviews / playInstalls are only ever populated on
 * "verified" entries, so the ratings carousel never shows a number that
 * wasn't confirmed against an actual store listing.
 */

function googleSearch(q: string) {
  return `https://www.google.com/search?q=${encodeURIComponent(q)}`;
}

export const LENDERS: Lender[] = [
  // ── Verified (direct Play Store fetch or multi-source cross-check) ──
  {
    id: "fairmoney",
    name: "FairMoney",
    monogram: "FM",
    kind: "Digital bank",
    operator: "FairMoney Microfinance Bank",
    summary: "High-volume instant lender with a full banking app and USSD fallback.",
    minAmount: 1500,
    maxAmount: 3000000,
    minIncome: 30000,
    aprMin: 24,
    aprMax: 120,
    monthlyRateMin: 2.5,
    monthlyRateMax: 30,
    terms: [3, 6, 12, 24],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://fairmoney.ng",
    iconUrl:
      "https://play-lh.googleusercontent.com/Hf2OGzogx5o1QvxJo9BTfXyzpvu0SMRArwyTILJ3OFpLff8_xYxHebPFdCV9XN2Jq_atqlzQobQP19p7rD0nmQ",
    sourceConfidence: "verified",
    platform: "Android · iOS · USSD (*322*9#)",
    playRating: 4.5,
    playReviews: "920K",
    playInstalls: "10M+",
    speed: 95,
    reliability: 80,
    approvalEase: 90,
    monthlyFlex: 55,
    aprQuality: 50,
  },
  {
    id: "carbon",
    name: "Carbon",
    monogram: "CB",
    kind: "Digital bank",
    operator: "Carbon Microfinance Bank",
    summary: "One of the longest-running apps in the market, with the clearest cost breakdown.",
    minAmount: 2500,
    maxAmount: 1000000,
    minIncome: 30000,
    aprMin: 54,
    aprMax: 195,
    monthlyRateMin: 4.5,
    monthlyRateMax: 30,
    terms: [2, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://www.getcarbon.co/loans",
    sourceConfidence: "verified",
    platform: "Android · iOS",
    playRating: 4.4,
    playInstalls: "1M+",
    speed: 85,
    reliability: 88,
    approvalEase: 78,
    monthlyFlex: 60,
    aprQuality: 60,
  },
  {
    id: "branch",
    name: "Branch",
    monogram: "BR",
    kind: "Loan app",
    operator: "Branch International Finance Company",
    summary: "Global lender with the lowest advertised floor rate of the big apps.",
    minAmount: 6000,
    maxAmount: 2000000,
    minIncome: 25000,
    aprMin: 34,
    aprMax: 270,
    monthlyRateMin: 3,
    monthlyRateMax: 23,
    terms: [2, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://branch.co",
    iconUrl:
      "https://play-lh.googleusercontent.com/XT4U66Oce5BD-ege-7dK5nSP8eCkAs4-XIygehZ3mfKat_hwIL2t1oz73fiAOxSvTTywC9NNMOElTK1ZVvqLieQ",
    sourceConfidence: "verified",
    platform: "Android",
    playRating: 4.5,
    playReviews: "3.46M",
    playInstalls: "50M+",
    speed: 88,
    reliability: 82,
    approvalEase: 85,
    monthlyFlex: 62,
    aprQuality: 68,
  },
  {
    id: "palmcredit",
    name: "PalmCredit",
    monogram: "PC",
    kind: "Loan app",
    operator: "Blooms Microfinance Bank (via PalmPay)",
    summary: "The fastest small-loan disbursal in this scan, built into the PalmPay wallet.",
    minAmount: 2000,
    maxAmount: 300000,
    minIncome: 20000,
    aprMin: 24,
    aprMax: 56,
    monthlyRateMin: 3,
    monthlyRateMax: 10,
    terms: [3, 6, 9, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://www.palmpay.com",
    iconUrl:
      "https://play-lh.googleusercontent.com/B4XsizC57wk0-a7nz-IRf7Dl-MJ5-9_Nd8s6EH_qmm2EB3V4FdWiyEizhzG0kk_G3hK7-yaVGNeMwqFKVxGxEQ",
    sourceConfidence: "verified",
    platform: "Android · iOS",
    playRating: 4.5,
    playReviews: "252K",
    playInstalls: "10M+",
    speed: 92,
    reliability: 70,
    approvalEase: 88,
    monthlyFlex: 45,
    aprQuality: 42,
  },
  {
    id: "renmoney",
    name: "Renmoney",
    monogram: "RM",
    kind: "Microfinance bank",
    operator: "Renmoney Microfinance Bank",
    summary: "Documentation-heavy but the cheapest rate floor here, for salaried earners wanting size.",
    minAmount: 5000,
    maxAmount: 6000000,
    minIncome: 150000,
    aprMin: 25,
    aprMax: 90,
    monthlyRateMin: 2.12,
    monthlyRateMax: 7.5,
    terms: [3, 6, 12, 24],
    fundingDays: { min: 0, max: 2 },
    states: "all",
    applyUrl: "https://www.renmoney.com",
    appStoreUrl: "https://apps.apple.com/ng/app/renmoney-mfb/id1491158086",
    sourceConfidence: "verified",
    platform: "Android · iOS · Web",
    playRating: 4.3,
    playInstalls: "1M+",
    speed: 55,
    reliability: 85,
    approvalEase: 45,
    monthlyFlex: 82,
    aprQuality: 78,
  },
  {
    id: "aella",
    name: "Aella Credit",
    monogram: "AC",
    kind: "Loan app",
    operator: "Aella Microfinance Bank",
    summary: "Loans, bill pay, and light health cover in one app, with a wide credit-tier spread.",
    minAmount: 2000,
    maxAmount: 1500000,
    minIncome: 25000,
    aprMin: 22,
    aprMax: 264,
    monthlyRateMin: 2,
    monthlyRateMax: 20,
    terms: [2, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://aellaapp.com",
    iconUrl:
      "https://play-lh.googleusercontent.com/83gcasalHXomDa-OGQPuFXkY9Anq03Tqf66_0kFkzoQrEdVGmJbY0xFke3dYHJnX_fcuso5Sk-FHWYBWdXSVahk",
    sourceConfidence: "verified",
    platform: "Android · iOS",
    playRating: 4.1,
    playReviews: "38.1K",
    playInstalls: "1M+",
    speed: 78,
    reliability: 72,
    approvalEase: 80,
    monthlyFlex: 58,
    aprQuality: 66,
  },
  {
    id: "kuda",
    name: "Kuda Overdraft",
    monogram: "KU",
    kind: "Digital bank",
    operator: "Kuda Microfinance Bank",
    summary: "Not a standalone loan — an overdraft on an active Kuda account, for short gaps only.",
    minAmount: 1000,
    maxAmount: 150000,
    minIncome: 50000,
    aprMin: 90,
    aprMax: 110,
    monthlyRateMin: 9,
    monthlyRateMax: 9,
    terms: [1, 2, 3],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://www.kuda.com/borrowing/",
    appStoreUrl: "https://apps.apple.com/ng/app/kuda-money-app-for-africans/id1467373738",
    sourceConfidence: "verified",
    platform: "Android · iOS",
    playRating: 4.5,
    playInstalls: "5M+",
    speed: 96,
    reliability: 78,
    approvalEase: 60,
    monthlyFlex: 30,
    aprQuality: 55,
  },
  {
    id: "moniepoint",
    name: "Moniepoint",
    monogram: "MP",
    kind: "Digital bank",
    operator: "Moniepoint Microfinance Bank",
    summary: "Backed by Nigeria's largest agent-banking network, now a nationally licensed MFB.",
    minAmount: 50000,
    maxAmount: 1000000,
    minIncome: 50000,
    aprMin: 30,
    aprMax: 90,
    monthlyRateMin: 2.5,
    monthlyRateMax: 15,
    terms: [1, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://moniepoint.com",
    sourceConfidence: "verified",
    platform: "Android · iOS",
    playRating: 4.6,
    playInstalls: "10M+",
    speed: 80,
    reliability: 84,
    approvalEase: 55,
    monthlyFlex: 68,
    aprQuality: 70,
  },
  {
    id: "quickcheck",
    name: "QuickCheck",
    monogram: "QC",
    kind: "Loan app",
    operator: "QuickCheck Technologies",
    summary: "Built for first-time borrowers with thin credit history, on a shorter leash.",
    minAmount: 1500,
    maxAmount: 500000,
    minIncome: 20000,
    aprMin: 30,
    aprMax: 84,
    monthlyRateMin: 5,
    monthlyRateMax: 15,
    terms: [1, 2, 3, 6],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://quickcheck.ng",
    sourceConfidence: "verified",
    platform: "Android",
    playRating: 4.5,
    speed: 82,
    reliability: 68,
    approvalEase: 84,
    monthlyFlex: 40,
    aprQuality: 48,
  },

  // ── Commercial banks (real institutions; official homepage domains) ──
  {
    id: "gtbank",
    name: "GTBank",
    monogram: "GT",
    kind: "Commercial bank",
    operator: "Guaranty Trust Bank",
    summary: "Traditional bank personal loans for salary account holders, larger and cheaper than app loans.",
    minAmount: 500000,
    maxAmount: 5000000,
    minIncome: 200000,
    aprMin: 20,
    aprMax: 36,
    monthlyRateMin: 1.33,
    monthlyRateMax: 3,
    terms: [6, 12],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://www.gtbank.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 40,
    reliability: 88,
    approvalEase: 35,
    monthlyFlex: 75,
    aprQuality: 85,
  },
  {
    id: "accessbank",
    name: "Access Bank",
    monogram: "AB",
    kind: "Commercial bank",
    operator: "Access Bank Plc",
    summary: "Nigeria's largest bank by customer base; salary-earner personal loans up to ₦5m.",
    minAmount: 10000,
    maxAmount: 5000000,
    minIncome: 100000,
    aprMin: 30,
    aprMax: 60,
    monthlyRateMin: 4,
    monthlyRateMax: 4,
    terms: [6, 12, 24, 36],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://www.accessbankplc.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 42,
    reliability: 86,
    approvalEase: 38,
    monthlyFlex: 78,
    aprQuality: 65,
  },
  {
    id: "zenithbank",
    name: "Zenith Bank",
    monogram: "ZB",
    kind: "Commercial bank",
    operator: "Zenith Bank Plc",
    summary: "Blue-chip commercial bank with personal loans for confirmed salary earners.",
    minAmount: 10000,
    maxAmount: 5000000,
    minIncome: 150000,
    aprMin: 60,
    aprMax: 108,
    monthlyRateMin: 9,
    monthlyRateMax: 9,
    terms: [6, 12, 24],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://www.zenithbank.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 40,
    reliability: 87,
    approvalEase: 35,
    monthlyFlex: 70,
    aprQuality: 40,
  },
  {
    id: "uba",
    name: "UBA Click Credit",
    monogram: "UB",
    kind: "Commercial bank",
    operator: "United Bank for Africa",
    summary: "Instant USSD loans (*919#) for existing UBA account holders, up to ₦15m for larger profiles.",
    minAmount: 5000,
    maxAmount: 15000000,
    minIncome: 80000,
    aprMin: 25,
    aprMax: 40,
    monthlyRateMin: 2.08,
    monthlyRateMax: 2.08,
    terms: [1, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://www.ubagroup.com/countries/ng/",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · USSD (*919#)",
    speed: 78,
    reliability: 84,
    approvalEase: 55,
    monthlyFlex: 80,
    aprQuality: 82,
  },
  {
    id: "fcmb",
    name: "FCMB",
    monogram: "FC",
    kind: "Commercial bank",
    operator: "First City Monument Bank",
    summary: "Mid-tier commercial bank; personal loans up to ₦2m for salaried and business customers.",
    minAmount: 50000,
    maxAmount: 2000000,
    minIncome: 100000,
    aprMin: 30,
    aprMax: 60,
    monthlyRateMin: 4,
    monthlyRateMax: 4,
    terms: [6, 12, 24],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://www.fcmb.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 38,
    reliability: 78,
    approvalEase: 35,
    monthlyFlex: 70,
    aprQuality: 62,
  },
  {
    id: "sterling",
    name: "Sterling Bank",
    monogram: "SB",
    kind: "Commercial bank",
    operator: "Sterling Bank Plc",
    summary: "Full-service bank with some of the longest personal-loan terms on this list, up to 5 years.",
    minAmount: 10000,
    maxAmount: 5000000,
    minIncome: 100000,
    aprMin: 40,
    aprMax: 60,
    monthlyRateMin: 5,
    monthlyRateMax: 5,
    terms: [12, 24, 36, 60],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://sterling.ng",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 36,
    reliability: 80,
    approvalEase: 34,
    monthlyFlex: 88,
    aprQuality: 60,
  },
  {
    id: "unionbank",
    name: "Union Bank",
    monogram: "UN",
    kind: "Commercial bank",
    operator: "Union Bank of Nigeria",
    summary: "One of Nigeria's oldest banks; the highest ceiling in this scan for salaried profiles.",
    minAmount: 50000,
    maxAmount: 30000000,
    minIncome: 150000,
    aprMin: 30,
    aprMax: 60,
    monthlyRateMin: 4,
    monthlyRateMax: 4,
    terms: [12, 24, 36, 60],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://www.unionbankng.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 34,
    reliability: 76,
    approvalEase: 30,
    monthlyFlex: 85,
    aprQuality: 65,
  },
  {
    id: "stanbicibtc",
    name: "Stanbic IBTC",
    monogram: "SI",
    kind: "Commercial bank",
    operator: "Stanbic IBTC Bank (Standard Bank Group)",
    summary: "Part of Standard Bank Group; large-ticket personal loans for corporate salary accounts.",
    minAmount: 50000,
    maxAmount: 15000000,
    minIncome: 200000,
    aprMin: 22,
    aprMax: 40,
    monthlyRateMin: 2,
    monthlyRateMax: 2,
    terms: [12, 24, 36, 48],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://www.stanbicibtcbank.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 36,
    reliability: 84,
    approvalEase: 32,
    monthlyFlex: 84,
    aprQuality: 80,
  },
  {
    id: "fidelitybank",
    name: "Fidelity Bank",
    monogram: "FB",
    kind: "Commercial bank",
    operator: "Fidelity Bank Plc",
    summary: "Personal loans and salary advances up to ₦10m for public and private sector employees.",
    minAmount: 50000,
    maxAmount: 10000000,
    minIncome: 120000,
    aprMin: 22,
    aprMax: 40,
    monthlyRateMin: 2,
    monthlyRateMax: 2,
    terms: [6, 12, 24, 36],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://www.fidelitybank.ng",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 37,
    reliability: 80,
    approvalEase: 33,
    monthlyFlex: 82,
    aprQuality: 80,
  },
  {
    id: "firstbank",
    name: "First Bank of Nigeria",
    monogram: "1B",
    kind: "Commercial bank",
    operator: "First Bank of Nigeria Ltd",
    summary: "130+ years in Nigerian banking; personal loans up to ₦15m for confirmed staff.",
    minAmount: 10000,
    maxAmount: 15000000,
    minIncome: 150000,
    aprMin: 20,
    aprMax: 35,
    monthlyRateMin: 1.83,
    monthlyRateMax: 1.83,
    terms: [3, 12, 24, 60],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://www.firstbanknigeria.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · Branch",
    speed: 38,
    reliability: 82,
    approvalEase: 34,
    monthlyFlex: 86,
    aprQuality: 84,
  },
  {
    id: "alat",
    name: "ALAT by Wema",
    monogram: "AL",
    kind: "Digital bank",
    operator: "Wema Bank",
    summary: "Nigeria's first fully digital bank; small unsecured loans directly in the app.",
    minAmount: 10000,
    maxAmount: 200000,
    minIncome: 30000,
    aprMin: 30,
    aprMax: 36,
    monthlyRateMin: 3,
    monthlyRateMax: 3,
    terms: [1, 3, 6],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://alat.ng",
    sourceConfidence: "aggregated",
    platform: "Android · iOS",
    speed: 85,
    reliability: 78,
    approvalEase: 65,
    monthlyFlex: 55,
    aprQuality: 68,
  },

  // ── Development finance / government-backed ──
  {
    id: "boi",
    name: "Bank of Industry",
    monogram: "BI",
    kind: "Development finance",
    operator: "Bank of Industry Ltd (Federal Government of Nigeria)",
    summary: "Government development bank funding SMEs and industry at concessional rates. Slow, but the cheapest ceiling here.",
    minAmount: 1000000,
    maxAmount: 50000000,
    minIncome: 0,
    aprMin: 10,
    aprMax: 10,
    monthlyRateMin: 0.83,
    monthlyRateMax: 0.83,
    terms: [12, 24, 36, 60],
    fundingDays: { min: 5, max: 20 },
    states: "all",
    applyUrl: "https://www.boi.ng",
    sourceConfidence: "aggregated",
    platform: "Web application",
    speed: 15,
    reliability: 75,
    approvalEase: 15,
    monthlyFlex: 95,
    aprQuality: 98,
  },
  {
    id: "nirsalmfb",
    name: "NIRSAL Microfinance Bank",
    monogram: "NM",
    kind: "Development finance",
    operator: "NIRSAL Microfinance Bank (Federal Government-backed)",
    summary: "Government-backed low-rate lending for agriculture, MSMEs, and targeted schemes.",
    minAmount: 1000000,
    maxAmount: 100000000,
    minIncome: 0,
    aprMin: 9,
    aprMax: 9,
    monthlyRateMin: 0.75,
    monthlyRateMax: 0.75,
    terms: [12, 24, 36, 60],
    fundingDays: { min: 5, max: 20 },
    states: "all",
    applyUrl: googleSearch("NIRSAL Microfinance Bank official site Nigeria"),
    sourceConfidence: "aggregated",
    platform: "Web application",
    speed: 12,
    reliability: 65,
    approvalEase: 12,
    monthlyFlex: 96,
    aprQuality: 99,
  },
  {
    id: "boa",
    name: "Bank of Agriculture",
    monogram: "BA",
    kind: "Development finance",
    operator: "Bank of Agriculture Ltd (Federal Government of Nigeria)",
    summary: "Federal agricultural development lender for farmers and agribusiness, slow but very cheap.",
    minAmount: 250000,
    maxAmount: 50000000,
    minIncome: 0,
    aprMin: 14,
    aprMax: 14,
    monthlyRateMin: 1.17,
    monthlyRateMax: 1.17,
    terms: [12, 24, 36, 60],
    fundingDays: { min: 5, max: 20 },
    states: "all",
    applyUrl: googleSearch("Bank of Agriculture Nigeria official site loan"),
    sourceConfidence: "aggregated",
    platform: "Branch application",
    speed: 10,
    reliability: 60,
    approvalEase: 12,
    monthlyFlex: 92,
    aprQuality: 96,
  },

  // ── More loan apps / microfinance banks (aggregated confidence) ──
  {
    id: "lapo",
    name: "LAPO Microfinance",
    monogram: "LP",
    kind: "Microfinance bank",
    operator: "LAPO Microfinance Bank",
    summary: "Long-established microfinance bank focused on underserved and rural communities.",
    minAmount: 30000,
    maxAmount: 150000,
    minIncome: 0,
    aprMin: 0,
    aprMax: 24,
    monthlyRateMin: 0,
    monthlyRateMax: 2,
    terms: [1, 3, 6, 8],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://lapo-nigeria.org",
    sourceConfidence: "aggregated",
    platform: "Branch · Field agents",
    speed: 30,
    reliability: 80,
    approvalEase: 45,
    monthlyFlex: 70,
    aprQuality: 88,
  },
  {
    id: "opay",
    name: "OPay",
    monogram: "OP",
    kind: "Digital bank",
    operator: "OPay Digital Services (Opera)",
    summary: "One of the two biggest mobile wallets in Nigeria; small in-wallet loans for active users.",
    minAmount: 3000,
    maxAmount: 50000,
    minIncome: 20000,
    aprMin: 36,
    aprMax: 60,
    monthlyRateMin: 3,
    monthlyRateMax: 5,
    terms: [3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://opayweb.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS · USSD (*955#)",
    speed: 90,
    reliability: 76,
    approvalEase: 82,
    monthlyFlex: 40,
    aprQuality: 46,
  },
  {
    id: "lidya",
    name: "Lidya",
    monogram: "LD",
    kind: "Loan app",
    operator: "Lidya Global",
    summary: "SME-focused working-capital loans, larger tickets than the consumer apps here.",
    minAmount: 100000,
    maxAmount: 2000000,
    minIncome: 0,
    aprMin: 30,
    aprMax: 48,
    monthlyRateMin: 4,
    monthlyRateMax: 4,
    terms: [1, 3, 6, 12, 24, 36],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://lidya.co",
    sourceConfidence: "aggregated",
    platform: "Web · Android",
    speed: 55,
    reliability: 72,
    approvalEase: 40,
    monthlyFlex: 65,
    aprQuality: 60,
  },
  {
    id: "baobab",
    name: "Baobab Microfinance",
    monogram: "BB",
    kind: "Microfinance bank",
    operator: "Baobab Group",
    summary: "Pan-African microfinance group; larger business loans with longer terms.",
    minAmount: 20000,
    maxAmount: 10000000,
    minIncome: 0,
    aprMin: 28,
    aprMax: 45,
    monthlyRateMin: 28,
    monthlyRateMax: 28,
    terms: [6, 12, 18, 24],
    fundingDays: { min: 2, max: 3 },
    states: "all",
    applyUrl: "https://baobabgroup.com",
    sourceConfidence: "aggregated",
    platform: "Branch application",
    speed: 30,
    reliability: 70,
    approvalEase: 35,
    monthlyFlex: 60,
    aprQuality: 55,
  },
  {
    id: "creditdirect",
    name: "Credit Direct",
    monogram: "CD",
    kind: "Loan app",
    operator: "Credit Direct Finance Company",
    summary: "Long-running consumer lender for employees and SMEs, larger amounts than most apps.",
    minAmount: 10000,
    maxAmount: 5000000,
    minIncome: 60000,
    aprMin: 0,
    aprMax: 60,
    monthlyRateMin: 3,
    monthlyRateMax: 5,
    terms: [1, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://creditdirect.ng",
    sourceConfidence: "aggregated",
    platform: "Android · iOS",
    speed: 65,
    reliability: 74,
    approvalEase: 55,
    monthlyFlex: 68,
    aprQuality: 65,
  },
  {
    id: "pagefinancials",
    name: "Page Financials",
    monogram: "PF",
    kind: "Loan app",
    operator: "Page Financials",
    summary: "Salary and business loans for individuals and SMEs, mid-size ticket range.",
    minAmount: 200000,
    maxAmount: 5000000,
    minIncome: 80000,
    aprMin: 40,
    aprMax: 60,
    monthlyRateMin: 5,
    monthlyRateMax: 5,
    terms: [1, 3, 6, 12],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: "https://pagefinancials.com",
    sourceConfidence: "aggregated",
    platform: "Android · Web",
    speed: 55,
    reliability: 68,
    approvalEase: 45,
    monthlyFlex: 62,
    aprQuality: 55,
  },
  {
    id: "specta",
    name: "Specta",
    monogram: "SP",
    kind: "Loan app",
    operator: "Sterling Bank",
    summary: "Sterling Bank's digital lending arm; large amounts marketed as approvable in minutes.",
    minAmount: 10000,
    maxAmount: 5000000,
    minIncome: 80000,
    aprMin: 40,
    aprMax: 60,
    monthlyRateMin: 5,
    monthlyRateMax: 5,
    terms: [1, 12, 24, 60],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("Specta Sterling Bank Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Web · Android",
    speed: 80,
    reliability: 72,
    approvalEase: 55,
    monthlyFlex: 80,
    aprQuality: 55,
  },
  {
    id: "quickteller",
    name: "Quickteller Loans",
    monogram: "QT",
    kind: "Loan app",
    operator: "Interswitch",
    summary: "Loan feature inside Interswitch's payments app, competitive quoted rate floor.",
    minAmount: 1000,
    maxAmount: 1000000,
    minIncome: 20000,
    aprMin: 24,
    aprMax: 24,
    monthlyRateMin: 2,
    monthlyRateMax: 2,
    terms: [1, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://quickteller.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS",
    speed: 75,
    reliability: 74,
    approvalEase: 60,
    monthlyFlex: 60,
    aprQuality: 78,
  },
  {
    id: "rosabon",
    name: "Rosabon Financial Services",
    monogram: "RF",
    kind: "Loan app",
    operator: "Rosabon Financial Services (Concept Group)",
    summary: "Consumer and asset finance company; leasing-style loans for salary earners.",
    minAmount: 100000,
    maxAmount: 1500000,
    minIncome: 80000,
    aprMin: 50,
    aprMax: 67,
    monthlyRateMin: 5.6,
    monthlyRateMax: 5.6,
    terms: [1, 3, 6, 8],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: googleSearch("Rosabon Financial Services Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Web · Branch",
    speed: 40,
    reliability: 62,
    approvalEase: 38,
    monthlyFlex: 55,
    aprQuality: 40,
  },
  {
    id: "umba",
    name: "Umba",
    monogram: "UM",
    kind: "Digital bank",
    operator: "Umba",
    summary: "Pan-African digital bank offering small instant loans alongside a free current account.",
    minAmount: 5000,
    maxAmount: 300000,
    minIncome: 20000,
    aprMin: 36,
    aprMax: 60,
    monthlyRateMin: 3,
    monthlyRateMax: 5,
    terms: [1, 3, 6],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://umbaapp.com",
    sourceConfidence: "aggregated",
    platform: "Android · iOS",
    speed: 78,
    reliability: 58,
    approvalEase: 68,
    monthlyFlex: 45,
    aprQuality: 45,
  },

  // ── Smaller loan apps (aggregated confidence; search-linked, not a guessed domain) ──
  {
    id: "c24",
    name: "C24",
    monogram: "C2",
    kind: "Loan app",
    operator: "C24",
    summary: "Larger-ticket instant loans marketed as approvable in five minutes.",
    minAmount: 50000,
    maxAmount: 5000000,
    minIncome: 40000,
    aprMin: 60,
    aprMax: 96,
    monthlyRateMin: 8,
    monthlyRateMax: 16,
    terms: [1, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("C24 loan app Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android",
    speed: 85,
    reliability: 45,
    approvalEase: 60,
    monthlyFlex: 40,
    aprQuality: 30,
  },
  {
    id: "fint",
    name: "FINT",
    monogram: "FT",
    kind: "Loan app",
    operator: "FINT",
    summary: "24-hour disbursement with one of the lower quoted monthly-rate floors in the long tail.",
    minAmount: 2000,
    maxAmount: 2000000,
    minIncome: 25000,
    aprMin: 24,
    aprMax: 24,
    monthlyRateMin: 2,
    monthlyRateMax: 2,
    terms: [1, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("FINT loan app Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android",
    speed: 70,
    reliability: 50,
    approvalEase: 55,
    monthlyFlex: 55,
    aprQuality: 78,
  },
  {
    id: "kiakia",
    name: "KiaKia",
    monogram: "KK",
    kind: "Loan app",
    operator: "KiaKia",
    summary: "Small, fast micro-loans aimed at same-hour cash gaps.",
    minAmount: 20000,
    maxAmount: 200000,
    minIncome: 20000,
    aprMin: 60,
    aprMax: 60,
    monthlyRateMin: 5,
    monthlyRateMax: 5,
    terms: [1],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("KiaKia loan app Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android",
    speed: 88,
    reliability: 48,
    approvalEase: 70,
    monthlyFlex: 20,
    aprQuality: 35,
  },
  {
    id: "sokoloan",
    name: "Sokoloan",
    monogram: "SK",
    kind: "Loan app",
    operator: "Sokoloan",
    summary: "Payday-style loans with a wide 7–190 day repayment window.",
    minAmount: 5000,
    maxAmount: 100000,
    minIncome: 20000,
    aprMin: 54,
    aprMax: 54,
    monthlyRateMin: 4.5,
    monthlyRateMax: 4.5,
    terms: [1, 3, 7],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("Sokoloan Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android",
    speed: 82,
    reliability: 46,
    approvalEase: 65,
    monthlyFlex: 55,
    aprQuality: 48,
  },
  {
    id: "migo",
    name: "Migo",
    monogram: "MG",
    kind: "Loan app",
    operator: "Migo",
    summary: "Embedded-credit lender best known for powering loans inside partner apps.",
    minAmount: 500,
    maxAmount: 500000,
    minIncome: 15000,
    aprMin: 60,
    aprMax: 60,
    monthlyRateMin: 5,
    monthlyRateMax: 5,
    terms: [1, 3, 6, 12],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("Migo loan Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android · Embedded",
    speed: 84,
    reliability: 52,
    approvalEase: 68,
    monthlyFlex: 45,
    aprQuality: 45,
  },
  {
    id: "creditville",
    name: "Creditville",
    monogram: "CV",
    kind: "Loan app",
    operator: "Creditville Limited",
    summary: "Mid-size personal loans with a two-day approval window.",
    minAmount: 100000,
    maxAmount: 4000000,
    minIncome: 60000,
    aprMin: 60,
    aprMax: 60,
    monthlyRateMin: 5,
    monthlyRateMax: 5,
    terms: [1, 6, 12, 18],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: googleSearch("Creditville Limited Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Web",
    speed: 45,
    reliability: 50,
    approvalEase: 40,
    monthlyFlex: 60,
    aprQuality: 42,
  },
  {
    id: "zedvance",
    name: "Zedvance",
    monogram: "ZV",
    kind: "Loan app",
    operator: "Zedvance Finance",
    summary: "Collateral-free consumer loans up to ₦5m, no explicit income floor advertised.",
    minAmount: 5000,
    maxAmount: 5000000,
    minIncome: 30000,
    aprMin: 42,
    aprMax: 42,
    monthlyRateMin: 3.5,
    monthlyRateMax: 3.5,
    terms: [1, 6, 12, 18],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("Zedvance Finance Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android · Web",
    speed: 65,
    reliability: 52,
    approvalEase: 55,
    monthlyFlex: 65,
    aprQuality: 60,
  },
  {
    id: "rapidcash",
    name: "RapidCash",
    monogram: "RC",
    kind: "Loan app",
    operator: "RapidCash",
    summary: "Very fast, very small loans — among the highest quoted rate floors in this scan.",
    minAmount: 10000,
    maxAmount: 50000,
    minIncome: 15000,
    aprMin: 90,
    aprMax: 90,
    monthlyRateMin: 31,
    monthlyRateMax: 31,
    terms: [1],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("RapidCash loan app Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android",
    speed: 90,
    reliability: 30,
    approvalEase: 70,
    monthlyFlex: 15,
    aprQuality: 15,
  },
  {
    id: "sociallender",
    name: "Social Lender",
    monogram: "SL",
    kind: "Loan app",
    operator: "Social Lender",
    summary: "Unusual model — loan eligibility driven by your social media footprint rather than BVN history.",
    minAmount: 1000,
    maxAmount: 100000,
    minIncome: 0,
    aprMin: 60,
    aprMax: 60,
    monthlyRateMin: 5,
    monthlyRateMax: 5,
    terms: [1],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("Social Lender Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android · Web",
    speed: 60,
    reliability: 40,
    approvalEase: 60,
    monthlyFlex: 30,
    aprQuality: 40,
  },
  {
    id: "jumiapay",
    name: "JumiaPay Loans",
    monogram: "JP",
    kind: "Loan app",
    operator: "Jumia Nigeria",
    summary: "Short-term micro-loans tied to the Jumia shopping and payments ecosystem.",
    minAmount: 1000,
    maxAmount: 100000,
    minIncome: 15000,
    aprMin: 42,
    aprMax: 42,
    monthlyRateMin: 3.5,
    monthlyRateMax: 3.5,
    terms: [1],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: "https://www.jumia.com.ng",
    sourceConfidence: "aggregated",
    platform: "Android · iOS",
    speed: 75,
    reliability: 55,
    approvalEase: 60,
    monthlyFlex: 30,
    aprQuality: 55,
  },
  {
    id: "loan35",
    name: "Loan35",
    monogram: "L3",
    kind: "Loan app",
    operator: "Loan35",
    summary: "Small consumer lender positioned around fast 24-hour turnaround.",
    minAmount: 50000,
    maxAmount: 2000000,
    minIncome: 40000,
    aprMin: 48,
    aprMax: 48,
    monthlyRateMin: 4,
    monthlyRateMax: 4,
    terms: [1, 12, 24, 60],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: googleSearch("Loan35 Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Web",
    speed: 50,
    reliability: 40,
    approvalEase: 45,
    monthlyFlex: 55,
    aprQuality: 55,
  },
  {
    id: "lendigo",
    name: "Lendigo",
    monogram: "LG",
    kind: "Loan app",
    operator: "Lendigo",
    summary: "SME working-capital lender, larger tickets with a two-day turnaround.",
    minAmount: 300000,
    maxAmount: 5000000,
    minIncome: 0,
    aprMin: 24,
    aprMax: 24,
    monthlyRateMin: 2,
    monthlyRateMax: 2,
    terms: [6, 12],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: googleSearch("Lendigo Nigeria SME loans official site"),
    sourceConfidence: "aggregated",
    platform: "Web",
    speed: 45,
    reliability: 45,
    approvalEase: 35,
    monthlyFlex: 60,
    aprQuality: 80,
  },
  {
    id: "spotyloans",
    name: "Spotyloans",
    monogram: "SY",
    kind: "Loan app",
    operator: "Spotyloans",
    summary: "Fast instant loans, moderate rate compared to the smallest micro-lenders.",
    minAmount: 1000,
    maxAmount: 1000000,
    minIncome: 20000,
    aprMin: 36,
    aprMax: 36,
    monthlyRateMin: 3,
    monthlyRateMax: 3,
    terms: [1],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("Spotyloans Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android · Web",
    speed: 82,
    reliability: 42,
    approvalEase: 65,
    monthlyFlex: 40,
    aprQuality: 62,
  },
  {
    id: "3dcfinance",
    name: "3DC Finance",
    monogram: "3D",
    kind: "Loan app",
    operator: "3DC Finance",
    summary: "Short-term loans up to ₦1m with a two-day approval window.",
    minAmount: 10000,
    maxAmount: 1000000,
    minIncome: 30000,
    aprMin: 120,
    aprMax: 120,
    monthlyRateMin: 10,
    monthlyRateMax: 10,
    terms: [1, 2, 3, 4],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: googleSearch("3DC Finance Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Web · Android",
    speed: 42,
    reliability: 38,
    approvalEase: 40,
    monthlyFlex: 30,
    aprQuality: 20,
  },
  {
    id: "efinance",
    name: "E-Finance",
    monogram: "EF",
    kind: "Loan app",
    operator: "E-Finance",
    summary: "Corporate and personal loans up to ₦5m for employees of partner companies.",
    minAmount: 100000,
    maxAmount: 5000000,
    minIncome: 60000,
    aprMin: 72,
    aprMax: 72,
    monthlyRateMin: 6,
    monthlyRateMax: 6,
    terms: [1, 3, 6, 9],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: googleSearch("E-Finance Nigeria loans official site"),
    sourceConfidence: "aggregated",
    platform: "Web",
    speed: 45,
    reliability: 42,
    approvalEase: 40,
    monthlyFlex: 50,
    aprQuality: 35,
  },
  {
    id: "fastcredit",
    name: "Fast Credit",
    monogram: "FS",
    kind: "Loan app",
    operator: "Fast Credit",
    summary: "Mid-ticket consumer loans, positioned similarly to the commercial-bank tier.",
    minAmount: 100000,
    maxAmount: 5000000,
    minIncome: 60000,
    aprMin: 48,
    aprMax: 48,
    monthlyRateMin: 4,
    monthlyRateMax: 4,
    terms: [1, 3, 6, 12, 15],
    fundingDays: { min: 1, max: 2 },
    states: "all",
    applyUrl: googleSearch("Fast Credit Nigeria loans official site"),
    sourceConfidence: "aggregated",
    platform: "Web",
    speed: 46,
    reliability: 44,
    approvalEase: 42,
    monthlyFlex: 55,
    aprQuality: 55,
  },
  {
    id: "ninimoney",
    name: "NiNiMoney",
    monogram: "NN",
    kind: "Loan app",
    operator: "Andes Network SPA Limited",
    summary: "Long-tenor micro-loans up to 300 days, low daily rate on paper.",
    minAmount: 5000,
    maxAmount: 999999,
    minIncome: 20000,
    aprMin: 3.65,
    aprMax: 35,
    monthlyRateMin: 0.3,
    monthlyRateMax: 3,
    terms: [3, 6, 10],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("NiNiMoney loan app Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android",
    speed: 80,
    reliability: 55,
    approvalEase: 65,
    monthlyFlex: 60,
    aprQuality: 60,
  },
  {
    id: "pettycash",
    name: "Pettycash",
    monogram: "PT",
    kind: "Loan app",
    operator: "Pettycash",
    summary: "Very small, very short loans for same-hour gaps.",
    minAmount: 5000,
    maxAmount: 50000,
    minIncome: 15000,
    aprMin: 144,
    aprMax: 144,
    monthlyRateMin: 12,
    monthlyRateMax: 12,
    terms: [1],
    fundingDays: { min: 0, max: 1 },
    states: "all",
    applyUrl: googleSearch("Pettycash loan app Nigeria official site"),
    sourceConfidence: "aggregated",
    platform: "Android",
    speed: 88,
    reliability: 35,
    approvalEase: 68,
    monthlyFlex: 15,
    aprQuality: 12,
  },
];

/**
 * The link a person should actually tap. Uses the affiliate/referral link
 * once you've added one for this provider; otherwise falls back to the
 * plain official apply link so the app is never broken while you're still
 * signing up for programs.
 */
export function getApplyLink(lender: Lender): string {
  return lender.affiliateUrl || lender.applyUrl;
}
